'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BasketballContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BasketballContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Games() As DbSet(Of Game)
    Public Overridable Property Game_Players() As DbSet(Of Game_Players)
    Public Overridable Property Game_Round_PlayerShots() As DbSet(Of Game_Round_PlayerShots)
    Public Overridable Property Game_Rounds() As DbSet(Of Game_Rounds)
    Public Overridable Property lu_Location() As DbSet(Of lu_Location)
    Public Overridable Property lu_Player() As DbSet(Of lu_Player)
    Public Overridable Property lu_Round() As DbSet(Of lu_Round)

End Class
