'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Game_Players
    Public Property id As Integer
    Public Property gameId As Integer
    Public Property playerId As Integer
    Public Property shootingOrder As Byte

    Public Overridable Property Game As Game
    Public Overridable Property lu_Player As lu_Player

End Class
