'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class lu_Round
    Public Property id As Integer
    Public Property roundNumber As Integer
    Public Property shotAttempts As Integer

    Public Overridable Property Game_Rounds As ICollection(Of Game_Rounds) = New HashSet(Of Game_Rounds)

End Class
